<?php

namespace HomeBundle\Repository;

/**
 * carriereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carriereRepository extends \Doctrine\ORM\EntityRepository
{
}
